### ISSUE TITLE
Fejl i bynavn + minor bug

### ISSUE THREAD

**Issue by MathiasReker** [shipmondo/prestashop_shipping_module#11]
![bug002](https://user-images.githubusercontent.com/26626066/65039059-b09a6e80-d951-11e9-81ce-94e45d7642e7.png)

**Comment by JanMSP** [comment]
1. Jeg prøver lige at kigge hvorfor den bliver encoded sådan i første omgang.
2. Når man udfører ordren oprettes en adresse i prestashop med pakkeshoppens adresse. Den sættes med det samme som slettet for at man ikke kan brugeren ikke kan vælge den i en ny ordre som deres adresse, hvilket for mig giver god mening.

**Comment by MathiasReker** [comment]
1. 👍 

2. Det fungerer godt i min optik. Adressen kommer også med på fakturaen, så det er OK. Jeg ville bare sikre mig, at det var den forventede adfærd. Jeg er i øvrigt enig.

**Comment by JanMSP** [comment]
Den er fikset i https://github.com/shipmondo/prestashop_shipping_module/commit/26315b7991db076a4bd88a577a005a2e852a4d0a .
Ved v1.3.0 blev det ændret til at bruge str_rot13 på JSON string som skal gemmes. det gjorde at encoded æøå mistede escaping og derved viste den det. Jeg har fjernet str_rot13 helt da jeg ikke kan finde grundet til den bliver brugt, og det ikke er hemmeligt det data vi gemmer.
