### ISSUE TITLE
Rækkefølge ulogisk

### ISSUE THREAD

**Issue by MathiasReker** [shipmondo/prestashop_shipping_module#12]
Hvis jeg vælger adresse: Guldstjernevej 4, så er det logisk at Guldstjernevej 1 er den første mulighed for pakkeshop.

![bug003](https://user-images.githubusercontent.com/26626066/65039265-23a3e500-d952-11e9-8f6b-420f8d34966b.png)

**Comment by MathiasReker** [comment]
@JanMSP har du et bud på en løsning? Jeg synes ikke at jeg kan se, at der skulle være noget galt i modulet. Er det et problem med API'et?

**Comment by JanMSP** [comment]
@MathiasReker Vi er gået over til en ny måde at udregne ruter på så nu skulle den gerne være løst :)
