### ISSUE TITLE
Leveringsadresse ikke opdateret

### ISSUE THREAD

**Issue by MathiasReker** [shipmondo/prestashop_shipping_module#2]
Leveringsadressen bliver ikke ændret til den pakkeshop som man vælger.

Gennemfør en ordre til pakkeshop -> Se leveringsadresse i BO.

**Comment by JanMSP** [comment]
Fixed i https://github.com/shipmondo/prestashop_shipping_module/commit/3b6a892e39a3e48e2bb35adc8cb6d31da38d62d6
Adresser blev ikke gemt efter ændring i original v1.3.0 af modullet.
