### ISSUE TITLE
Ikke muligt at vælge pakkeshop

### ISSUE THREAD

**Issue by MathiasReker** [shipmondo/prestashop_shipping_module#23]
@JanMSP Fejlen er løst, men jeg kan ikke længere vælge pakkeshop: https://reker.dk/0004.webm

_Originally posted by @MathiasReker in https://github.com/shipmondo/prestashop_shipping_module/issues/8#issuecomment-533028890_

**Comment by JanMSP** [comment]
Det skulle være muligt nu :)
