### ISSUE TITLE
Fejl i udleveringssted knap

### ISSUE THREAD

**Issue by MathiasReker** [shipmondo/prestashop_shipping_module#4]
Hvis jeg klikker på "Vælg udleveringsted" som bliver udleveringstederne tredoblet.

![image](https://user-images.githubusercontent.com/26626066/63614815-3857bc00-c5e4-11e9-8b52-30ea27c4715e.png)

![image](https://user-images.githubusercontent.com/26626066/63614856-4d344f80-c5e4-11e9-8a20-411e4acc1ddf.png)

**Comment by JanMSP** [comment]
Jeg har fixet det som gav fejlen. Men samtidig har jeg fjernet knappen for radio da den ikke giver mening når vi nu vælger den første som standard
