### ISSUE TITLE
No translations

### ISSUE THREAD

**Issue by JanMSP** [shipmondo/prestashop_shipping_module#41]
There are no translations

**Comment by JanMSP** [comment]
@MathiasReker Ville du kigge på denne? :)

**Comment by JanMSP** [comment]
Eller vise hvordan du ville gøre. Så kan vi implementere det

**Comment by MathiasReker** [comment]
Du kan oversætte i BO. brug denne sti: `/admin-dev/index.php/improve/international/translations`

**Comment by MathiasReker** [comment]
PR: https://github.com/shipmondo/prestashop_shipping_module/pull/42
