### ISSUE TITLE
Module is in the "Other" category

### ISSUE THREAD

**Issue by JanMSP** [shipmondo/prestashop_shipping_module#43]
Should be in "Shipping & Logistics"

**Comment by JanMSP** [comment]
Har du et fix til denne, @MathiasReker ? Er det fordi man selv uploader modullet?

**Comment by MathiasReker** [comment]
Det er en bug i PrestaShop. Du kan ikke gøre noget ved det, fordi det skal løses i PrestaShops kerne. :)
