### ISSUE TITLE
valgmulighed et skal være default

### ISSUE THREAD

**Issue by MathiasReker** [shipmondo/prestashop_shipping_module#5]
Valgmulighed et bør altid være default:

![image](https://user-images.githubusercontent.com/26626066/63615911-b6b55d80-c5e6-11e9-81f9-a78a40ed13e4.png)

**Comment by JanMSP** [comment]
Will be added in 1.3.1 release. Commit: https://github.com/shipmondo/prestashop_shipping_module/commit/f701eac787cb1e5a43d63a9fe48fbceab06c4a4c
