### ISSUE TITLE
Plugin doesn't work in PreshaShop 8+

### ISSUE THREAD

**Issue by korsgaard** [shipmondo/prestashop_shipping_module#54]
Several error. For example you are using functions removed from Prestashop core:
[Tools::jsonEncode and Tools::jsonDecode](https://github.com/PrestaShop/PrestaShop/commit/c1d84724067c6fecf75745b9f7eb8d419fe9002d)

**Comment by korsgaard** [comment]
Any news on this?

**Comment by JanMSP** [comment]
We expect to release a new Prestashop 8 compatible version in beginning of April.
