### ISSUE TITLE
Udleveringstedet bliver ikke gemt

### ISSUE THREAD

**Issue by MathiasReker** [shipmondo/prestashop_shipping_module#6]
Vælg udleveringsted:
![image](https://user-images.githubusercontent.com/26626066/63616259-71ddf680-c5e7-11e9-9770-3ab15e29e218.png)

Gå til betaling:
![image](https://user-images.githubusercontent.com/26626066/63616271-7b675e80-c5e7-11e9-9020-2895b6a2c18f.png)

Gå tilbage til leveringsmotode:
![image](https://user-images.githubusercontent.com/26626066/63616282-88844d80-c5e7-11e9-8f54-f2a4fb509a20.png)

Udleveringstedet bliver ikke gemt.

**Comment by JanMSP** [comment]
Fixed i rewrite branch for radio knapper. Kigger forsat på popup og dropdown

**Comment by JanMSP** [comment]
Fixed for dropdown og popup. Den er dog ikke valgt i popuppen, da man kun ville åbne den for at vælge en ny
