### ISSUE TITLE
Bug in checkout flow

### ISSUE THREAD

**Issue by MathiasReker** [shipmondo/prestashop_shipping_module#8]
Clear cookie -> add a product to cart -> go to checkout -> see exception

![Screenshot_2019-09-04 Screenshot](https://user-images.githubusercontent.com/26626066/64298740-e402f380-cf76-11e9-9f4b-611b663e210c.png)

**Comment by JanMSP** [comment]
@MathiasReker Jeg kan ikke genskabe den med de steps du skriver.
Kan du genskabe den hver gang?
Clear du også local storage?

**Comment by MathiasReker** [comment]
@JanMSP Jeg vil prøve om jeg kan reproducere problemet ud fra nyeste branch. Jeg vender tilbage meget snart.

**Comment by MathiasReker** [comment]
Prestashop 1.7.6.1
PHP 7.2
Apache

Start med at rydde cookies, i browseren. Herefter følg video: https://reker.dk/bug001.webm

**Comment by MathiasReker** [comment]
Det er vigtigt at debug_mode er aktiveret. :-)

**Comment by JanMSP** [comment]
Super jeg prøver igen :)

**Comment by JanMSP** [comment]
@MathiasReker Hey vil du teste igen? Jeg har fjernet den ligne der skabte fejlen fordi den ikke blev brugt til noget. **OBS!:** Jeg har renamet modulet til Shipmondo, altså skal du lægge filerne i en mappe der hedder "shipmondo" i stedet for "pakkelabels_shipping" inden du zipper det. Den vil også oprette nye carriers.

**Comment by MathiasReker** [comment]
@JanMSP Jeps, jeg er helt med - jeg har læst alle dine rettelser 😄 

Jeg tester og vender tilbage.

**Comment by MathiasReker** [comment]
@JanMSP Fejlen er løst, men jeg kan ikke længere vælge pakkeshop: https://reker.dk/0004.webm

**Comment by MathiasReker** [comment]
Lukker pga. løst.
